### ISSUE TITLE
Dashes are valid YouTube IDs

### ISSUE THREAD

**Issue by rockobonaparte** [mkly/youtube-closed-captions#1]
The validation regex in storage.py rejects dashes. However, those are a valid part of YouTube video IDs.

I can try to eventually send up a PR, but it's a simple job of just added a dash in the regexes:

```
import re
import os


class Storage():

    def __init__(self, video_id: str) -> None:
        self.video_id = video_id

    def get_file_path(self) -> str:
        if re.search(r'[^A-z0-9-]', self.video_id):
            raise ValueError(
                'Invalid video id attempting to write to filesystem')

        return 'subtitle_{0}.en.vtt'.format(
            re.sub(r'[^A-z0-9-]', '', self.video_id))

    def remove_file(self) -> None:
        os.remove(self.get_file_path())
```
An example with a dash: Gt-VQGNiSWU
(I was scraping the Spanish Flu Pandemic series for a speech project.)

**Comment by mkly** [comment]
Hello!
Thanks so much for sending this in. Apologies that it took so long for me to catch up to it. I've merged that into the master branch so hopefully that prevents the next person from getting stuck. :tropical_drink: 

Best Regards,
Mike
