### ISSUE TITLE
Automatic captions

### ISSUE THREAD

**Issue by CartierPierre** [mkly/youtube-closed-captions#2]
Hi,
does this package work with automatic generated captions ? I'm looking for french captions, nvm if it's a proper caption or just an automatic one.
Let me know if you think it's possible.

**Comment by mkly** [comment]
Hello!
Sorry I missed this issue. I have now pushed an update that should support captions in other languages. You can use it like
```
captions = download.get_captions(video_id, 'fr')
```
Note that it is **fr** as opposed to **fr-FR**
