### ISSUE TITLE
Fails test_real_video functional test

### ISSUE THREAD

**Issue by spatzlsberger** [mkly/youtube-closed-captions#5]
..F...............
======================================================================
FAIL: test_video_french (test.functional.test_real_video.TestRealVideo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "\repos\youtube-closed-captions\test\functional\test_real_video.py", line 22, in test_video_french
    video_id, 'fr')[:len(excerpt)])
AssertionError: "J'ai fini Jouons quelques LoL (League of Legends). Oh mo" != "J'ai fini Jouons à LoL (League of Legends). Oh mon Dieu,"
- J'ai fini Jouons quelques LoL (League of Legends). Oh mo
?                  ^^^^^^^^
+ J'ai fini Jouons à LoL (League of Legends). Oh mon Dieu,
?                  ^                               +++++++

Looks like the caption on the video itself was changed, not that the code is actually doing anything wrong.

**Comment by mkly** [comment]
Hello!
Thank you for the report. And even better a solution! I've updated the translation and also updated the youtube_dl dependency to a more recent version. Let me know if you have any additional issues. :tropical_drink:
